pagopa/selfcare-infra

- src/core/.terraform.lock.hcl
- src/core/env/dev/backend.ini
- src/core/env/dev/backend.tfvars
- src/core/env/dev/terraform.tfvars
- src/core/env/prod/backend.ini
- src/core/env/prod/backend.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/backend.ini
- src/core/env/uat/backend.tfvars
- src/core/env/uat/terraform.tfvars
- src/core/main.tf
fixed subscription names + upgraded provider versions
---
> fixed subscription names + upgraded provider versions

- src/core/monitor.tf
- src/core/security.tf
email and slack notification
appInsight key in key vault
---
> email and slack notification + appInsight key in key vault

- src/k8s/secrets.tf
- src/k8s/selc_secrets.tf
interop common aks secrets
---
> interop common secrets

- src/core/api/party_process/v1/confirmOnboarding_policy.xml
- src/core/api/party_process/v1/invalidateOnboarding_policy.xml
- src/core/apim.tf
mocking complete onboarding API
---
> mocking complete onboarding API

- src/core/env/prod/terraform.tfvars
contracts delete retention in PROD setted to 14 days
- [x Update configuration to existing resources
---
> contracts delete retention in PROD setted to 14 days

- src/core/api/party_management/v1/party-management.yml.tpl
- src/core/api/party_process/v1/getOnBoardingInfo_policy.xml
- src/core/api/party_process/v1/party-process.yml.tpl
- src/core/api/party_registry_proxy/v1/searchInstitution_policy.xml
party process and party management openApi updated
---
> Party process openapi updated

- src/core/storage_contracts.tf
- src/k8s/secrets.tf
- src/k8s/selc_secrets.tf
- src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
- src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
- src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
- src/k8s/variables.tf
interop services common secret fixed values
---
> interop services common secret fixed values

- src/core/api/party_process/v1/getOnBoardingInfo_policy.xml
update mock of party process to serve OnBoardingInfo to dashboard FE
---
> mock updated to serve dashboard FE

- src/core/apim.tf
- src/k8s/selc_configmaps.tf
config-map to provide services inner url
fixed apim basePath for interop services 
---
> configMap inner-service-url

- src/core/apim.tf
fix dashboard api version set defined for v1
fixed version set of dashboard api v1
---
> fixed dashboad api version set use

- src/core/api/party_process/v1/getOnBoardingInfo_policy.xml
updated mocks of partyProcess to serve new constants
---
> party-process mock updated to use new constants

- src/modules/azurerm_cosmosdb_account/main.tf
> Enable cosmosdb continuos backup

- src/k8s/selc_secrets.tf
defining postgres port in secret
---
> defining postgres_port

- src/core/api/party_process/v1/getOnBoardingInfo_policy.xml
mock updated to have active product
---
> mock updated to have active product

- src/core/apim.tf
- src/k8s/rbac.tf
- src/k8s/selc_configmaps.tf
- src/k8s/selc_ingress.tf
URL of interop-services updated + role pod_reader (required by interop-services)
---
> fixed interop-services configuration

- src/core/appgateway.tf
> Logging appgw

- src/core/monitor.tf
application insight will use log analytics workspace
---
> application insight will use log analytics workspace

- src/core/api/party_process/v1/getOnBoardingInfo_policy.xml
- src/core/api/party_process/v1/onboardingOrganization_policy.xml
- src/core/api/party_process/v1/retrieveInstitutionProducts_policy.xml
- src/core/api/party_registry_proxy/v1/getInstitutionById_policy.xml
- src/core/apim.tf
> Mocks updated

- src/core/dns_public.tf
> review dns

- src/k8s/selc_configmaps.tf
add email as spid info requested
Sctrictly necessary to userRegistry
---
> [SELC-284] add email as spid info requested

- src/core/api/party_process/v1/confirmOnboarding_policy.xml
> mock updated

- src/core/api/party_process/v1/confirmOnboarding_policy.xml
- src/k8s/selc_configmaps.tf
- src/k8s/selc_secrets.tf
- src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
- src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
- src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
- src/k8s/variables.tf
update aks configMap/secrets
---
> update aks config/secret

- src/core/apim.tf
- src/core/dns_private.tf
- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
- src/core/redis_cache.tf
- src/core/variables.tf
add redis private endpoints
redis private access and cost savings
this pr contains breaking changes (we need to destroy and recreate redis cache)
- DEV: to be applied
- UAT: applied
- PROD: not apply until spid verification process complete
---
> redis review

- src/k8s/selc_configmaps.tf
Update vat number to due compatible with iso format
because spid agid validator
---
> [SELC-284] update vat number to spid validation

- src/k8s/selc_configmaps.tf
fixed party process mail path
---
> fixed mail template path

- src/core/dns_public.tf
add delegation for io.selfcare.pagopa.it dns zone
ask delegation for io-selfcare https://github.com/pagopa/io-infra/pull/55
---
> Delegate io dns zone

- src/core/security_kv.tf
<\!\-\-\- Please always add a PR description as if nobody knows anything about the context these changes come from. \-\->
<\!\-\-\- Even if we are all from our internal team, we may not be on the same page. \-\->
<\!\-\-\- Write this PR as you were contributing to a public OSS project, where nobody knows you and you have to earn their trust. \-\->
<\!\-\-\- This will improve our projects in the long run\! Thanks. \-\->
\#\#\# List of changes
added group developer to kv in UAT e PROD
\#\#\# Motivation and context
without this change is impossible for ours collegues to change the secrets in KV
\#\#\# Type of changes
\- \[x\] Add new resources
\- \[x\] Update configuration to existing resources
\- \[ \] Remove existing resources
\#\#\# Env to apply
\- \[ \] DEV
\- \[x\] UAT
\- \[ \] PROD …
> added developer group to kv access policy

- src/k8s/selc_configmaps.tf
- src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
- src/k8s/variables.tf
Add variable name to config map about jwt token eschange duration
Debug integration test with other back office
---
> SELC Added a new variable to jwt exchage dur

- src/core/.terraform.lock.hcl
- src/core/cdn.tf
- src/core/dns_public.tf
- src/core/main.tf
- src/core/monitor.tf
added monitor web availability test setup
Have test for certificates status
> Infra 427 monitor web availability test setup

- src/core/env/uat/terraform.tfvars
* enabled autoscaling for uat
* enabled cosmosdb autoscaling for uat
> cosmosdb: enabled autoscaling for uat

- .github/workflows/tag-release.yaml
* added pipeline tag release
allow the creation of a tag, with convential commits
> pipeline for tag creationg following conventional commits

- src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
- src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
- src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
Added configuration of SIGNATURE_VALIDATION_ENABLED variable in partyProcess configMap
---
> added SIGNATURE_VALIDATION_ENABLED variable

- .devops/code-review-pipelines.yml
> fix: disabling code-review on push

- src/k8s/selc_secrets.tf
fixed notification-manager email
---
> fixed ms-notification-manager config

- src/core/env/uat/terraform.tfvars
UAT mongoDb configured as Serverless
---
> UAT mongoDb configured as Serverless

- src/core/mongodb.tf
- src/k8s/locals.tf
- src/k8s/selc_secrets.tf
added db selcUserGroups and userGroups collection
before to apply:
* Set the property lock_enable to false on module.mongdb_collection_products
* Import the already existent products collection using the following statement (fixing the reference to the ENV)
*  `./terraform.sh import dev module.mongdb_collection_products.azurerm_cosmosdb_mongo_collection.this "/subscriptions/1ab5e788-3b98-4c63-bd05-de0c7388c853/resourceGroups/selc-d-cosmosdb-mongodb-rg/providers/Microsoft.DocumentDB/databaseAccounts/selc-d-cosmosdb-mongodb-account/mongodbDatabases/selcProduct/collections/products"`
* Restore the lock_enable to true
* Apply core and then k8s modules
---
> SELC-588 SELC-615 userGroups collection

- src/core/mongodb.tf
- src/k8s/locals.tf
- src/k8s/selc_secrets.tf
This reverts commit 1fb7e85205aff1438c368f909ab0efe488269746.
reverted PR#136
---
> Revert "SELC-588 SELC-615 userGroups collection (#136)"

- src/k8s/selc_configmaps.tf
- src/k8s/selc_secrets.tf
Added secret cdn-storage
Updated ms-product config
---
> SELC-472 secret cdn-storage + ms-product config

- src/k8s/selc_configmaps.tf
fixed ENV_VAR name in common configMap
---
> fixed common env var name

- src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
- src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
- src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
Added ENABLED_CONFIDENTIAL_FILTER variable in common ConfigMap
---
> Added ENABLED_CONFIDENTIAL_FILTER variable in common ConfigMap

- src/k8s/selc_configmaps.tf
- src/k8s/variables.tf
JWT duration extended to 9 hours
---
> jwt duration extended to 9 hours

- src/k8s/selc_secrets.tf
- src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
- src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
- src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
Added userreg URL to common configMap
---
> Added userreg url to common configMap

- src/k8s/selc_configmaps.tf
- src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
- src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
- src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
- src/k8s/variables.tf
JWT audience configurable
- [x ] Update configuration to existing resources
---
> Selc 561 jwt audience

- src/k8s/serviceaccounts.tf
Privileges to run helm on azure devops
---
> Helm chart deployer privileges

- src/core/appgateway.tf
- src/core/monitor.tf
Fixed applicationGateway exposure of health check
---
> Fixed applicationGateway exposure of health check

- src/core/README.md
- src/core/apim.tf
- apim in uat and prod
- allow try and error in UAT and PROD
---
> Apim-upgrade-module

- src/core/resources/templates/email/user_activated.ftlh
- src/core/resources/templates/email/user_added_multi_role.ftlh
- src/core/resources/templates/email/user_added_single_role.ftlh
- src/core/resources/templates/email/user_deleted.ftlh
- src/core/resources/templates/email/user_suspended.ftlh
> updated mail templates

- src/core/README.md
- src/core/cdn.tf
- src/core/oneTrust.tf
- src/core/resources.tf
- src/core/resources/templates/email/user_activated.ftlh
- src/core/resources/templates/email/user_added_multi_role.ftlh
- src/core/resources/templates/email/user_added_single_role.ftlh
- src/core/resources/templates/email/user_deleted.ftlh
- src/core/resources/templates/email/user_suspended.ftlh
- src/k8s/ingress.tf
- src/k8s/main.tf
- fix to allow UAT and PROD installation
---
> Road-to-prod-may-22

- src/core/README.md
- src/core/dashboards/monitoring.json.tpl
- src/core/monitor.tf
Added monitoring dashboard
---
> Selc 439 monitoring dashboard

- src/core/env/uat/terraform.tfvars
> PIN-1456-update-dns: Update interop dns values

- src/core/api/party_process/v1/open-api.yml.tpl
- src/core/apim.tf
updated partyProcess openApi
bulkInstitution added to API able to be rewritten with Authorization header
---
> Party process open api update

- src/core/env/prod/terraform.tfvars
> pin-1544-interop-prod-dns: Interop prod domain delegation

- src/core/oneTrust.tf
Fix typo in oneTrust upload
With this fix now is possible to upload oneTrust contents
---
> fix: Fix typo in one trust upload

- src/core/contracts_template/interop/1.0.0/interop-accordo_di_adesione-v.1.0.0.html
added new version of interop contract
---
> SELC-1237new interop contract

- src/core/env/dev/terraform.tfvars
> update Interop dev domain delegation

- src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
> removing filter for uat env

- src/core/README.md
- src/core/api/ms_external_api/v1/open-api.yml.tpl
- src/core/apim.tf
This PR is for adding the new Externa API proxy service to the APIM 
Added a new module and resource
Needed for products BO integration
---
> add external api service to apim

- src/core/api/party_process/getInstitution_op_policy.xml.tpl
- src/core/api/party_process/v1/open-api.yml.tpl
- src/core/apim.tf
> add institution logo field to external api

- src/core/api/ms_external_api/v1/open-api.yml.tpl
- src/core/apim.tf
Add new API into external api for retrieving all the products of an institution and for the logged user
new required api
---
> add new getInstitutionUserProducts api to apim

- src/core/api/ms_external_api/v1/open-api.yml.tpl
- src/core/api/ms_user_group/v1/open-api.yml.tpl
- src/core/api/party_management/v1/open-api.yml.tpl
- src/core/api/party_process/v1/open-api.yml.tpl
> add x-selfcare-uid header parameter to all external API definitions

- src/core/api/ms_external_api/getInstitution_op_policy.xml.tpl
- src/core/api/ms_external_api/jwt_auth_op_policy_user_group.xml.tpl
- src/core/api/ms_external_api/v1/open-api.yml.tpl
- src/core/api/ms_user_group/v1/open-api.yml.tpl
- src/core/apim.tf
> move all external API into a single OpenAPI definition

- src/k8s/README.md
- src/k8s/secrets.tf
- src/k8s/selc_secrets.tf
> SELC-1199 adding new key vault for product external api

- src/core/developer.tf
- src/core/env/prod/developer/external/index.html
- src/core/env/uat/developer/external/index.html
- src/core/resources.tf
- src/core/security_kv.tf
adding --overwrite to save file that still existing on azure
---
> Fix developer portal

- src/k8s/secrets.tf
- src/k8s/selc_secrets.tf
Adding institution digital address for test as new secrets, avoiding writing private email on github 
---
> feat: Adding new secrets for test institution digital address

- src/core/env/prod/terraform.tfvars
Setting var Apim Pricing tier on Prod env to Premium
Prod env apim need SLA
---
> fix: Upgrade Selfcare Apim Pricing tier on Prod env to Premium

- src/core/monitor.tf
- src/core/variables.tf
- minor fix
- added action group for errors
Allow to have a channel dedicated to critical errors
---
> feat: Added New-action-alert-prod-error

- src/core/env/dev/terraform.tfvars
Updating Kubernates
Update Kubernates to new minor version
---
> fix: Bump Kubernates version 1.23.12

- src/core/api/ms_external_api/v1/open-api.yml.tpl
Updating list of enum product status on External API @apim
Adding new status:
- ACTIVE
- INACTIVE
- PHASE_OUT
- TESTING
- [] Yes, users may be impacted applying this change
---
> fix: Update apim get product

- src/core/api/ms_external_api/v1/open-api.yml.tpl
> fix: Status user-groups

- CODEOWNERS
Added Kevin to CODEOWNERS file
Added Kevin to codeowners file since he was not added at an earlier date.
---
> Added Kevin to CODEOWNERS 

- src/core/api/ms_external_api/v1/open-api.yml.tpl
Added institutionType filter to getProduct api in External Api 
Modified the backend microservice in order to retrieve the correct contract based on the institutionType
---
> added institutionType filter parameter to getProduct api in external-api

- src/core/README.md
- src/core/api/ms_product/v1/open-api.yml.tpl
- src/core/apim.tf
Added new Selfcare Product API for later user by party to set the placeholders when sending emails to user during new Onboardings. 
The previuous API getProduct that is exposed in the V1 version on ExternalAPI won't have the possibility to filter the product by its Id since the ID will be retrieved directly from the subscription Key. So this API is will expose the getProduct API with the possibility to pass a specific productId
---
> Added new API SelfCare Product Microservice to APIM

- src/k8s/README.md
- src/k8s/secrets.tf
- src/k8s/selc_configmaps.tf
- src/k8s/selc_secrets.tf
- src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
- src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
- src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
- src/k8s/variables.tf
Added configMap and secret to integrate aruba sign service
---
> creating aruba-sign-service configMap and secret

- src/core/contracts_template/pn/1.0.0/pn-accordo_di_adesione-v.1.0.0.html
> addition of a first version of the new "pn" contract

- src/k8s/README.md
- src/k8s/secrets.tf
- src/k8s/selc_configmaps.tf
- src/k8s/selc_secrets.tf
- src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
- src/k8s/variables.tf
Adding new secrets and configmap for infocamere ms-party-regsitry-proxy
---
> Adding new secrets and configmap for infocamere service

- src/core/env/prod/developer/external/v1/index.html
- src/core/env/prod/developer/external/v2/index.html
- src/core/env/uat/developer/external/v1/index.html
- src/core/env/uat/developer/external/v2/index.html
> fix-developer-portal

- src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
- src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
Adding vars fonr Geo tassonomies Microservices url
---
> fix-get-tax-var

- src/core/api_product/io-sign/policy.xml
- src/core/apim.tf
- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
Adding subscription key for eventhub and apim for io-sign product
---
> feat: Adding subscription key for IO-Sign product

- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
Update subnet for UAT and PROD
---
> fix: UAT and PROD subnet

- src/core/04_appgateway.tf
- src/domains/pnpg-app/env/dev/terraform.tfvars
- src/domains/pnpg-common/99_variables.tf
> working on

- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
- src/domains/pnpg-app/10_selc_configmaps.tf
- src/domains/pnpg-app/99_variables.tf
- src/domains/pnpg-app/README.md
- src/domains/pnpg-app/env/dev/terraform.tfvars
> Pnph configmap party process

- src/aks-platform/.terraform.lock.hcl
- src/aks-platform/03_aks_0.tf
- src/aks-platform/05_keda.tf
- src/aks-platform/README.md
- src/aks-platform/env/dev01/terraform.tfvars
- src/aks-platform/env/prod01/backend.tfvars
- src/aks-platform/env/prod01/terraform.tfvars
- src/aks-platform/env/uat01/backend.tfvars
- src/aks-platform/env/uat01/terraform.tfvars
- src/core/.terraform.lock.hcl
- src/core/03_network_aks_domains.tf
> feat: AKS platform setup for UAT and PROD

- src/domains/pnpg-app/.terraform.lock.hcl
- src/domains/pnpg-app/01_secrets.tf
- src/domains/pnpg-app/99_main.tf
- src/domains/pnpg-app/README.md
- src/domains/pnpg-app/env/prod/terraform.tfvars
- src/domains/pnpg-app/env/uat/terraform.tfvars
- src/domains/pnpg-common/README.md
> feat: Pnpg completed infra in UAT and PROD

- src/domains/pnpg-app/10_selc_configmaps.tf
- src/domains/pnpg-app/99_variables.tf
- src/domains/pnpg-app/env/dev/terraform.tfvars
- src/domains/pnpg-app/env/prod/terraform.tfvars
- src/domains/pnpg-app/env/uat/terraform.tfvars
> Fix-jwt-configmap

- src/domains/pnpg-app/10_selc_secrets.tf
- src/domains/pnpg-app/99_variables.tf
- src/k8s/locals.tf
Adding custom configuration to configmap
---
> fix: Add custom configuration

- src/domains/pnpg-app/10_selc_ingress.tf
- src/domains/pnpg-common/00_data.tf
- src/domains/pnpg-common/01_key_vault_operations.tf
- src/domains/pnpg-common/01_keyvault_0.tf
- src/domains/pnpg-common/README.md
> fix duplicate data apim

- src/domains/pnpg-app/06_selc_apim_pnpg.tf
- src/domains/pnpg-app/99_main.tf
- src/domains/pnpg-app/99_variables.tf
- src/domains/pnpg-app/api/external_api_data_vault/v1/getInstitution_op_policy.xml.tpl
- src/domains/pnpg-app/env/dev/terraform.tfvars
- src/domains/pnpg-app/env/prod/terraform.tfvars
- src/domains/pnpg-app/env/uat/terraform.tfvars
- src/domains/pnpg-common/99_outputs.tf
- src/domains/pnpg-common/env/uat/terraform.tfvars
> fix: Apim authentication without k8s

- src/domains/pnpg-app/06_selc_apim_pnpg.tf
- src/domains/pnpg-app/99_main.tf
- src/domains/pnpg-app/99_variables.tf
- src/domains/pnpg-app/api/external_api_data_vault/v1/getInstitution_op_policy.xml.tpl
- src/domains/pnpg-app/env/dev/terraform.tfvars
- src/domains/pnpg-app/env/prod/terraform.tfvars
- src/domains/pnpg-app/env/uat/terraform.tfvars
- src/domains/pnpg-common/99_outputs.tf
- src/domains/pnpg-common/env/uat/terraform.tfvars
> Fix apim auth

- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
> fix: Add new IP for PN on eventhub

- src/core/99_variables.tf
- src/core/README.md
- src/core/azure_devops_agent.tf
- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
Granting Get and List privileges to azdevops app projects principal on DEV and UAT
---
> feat: granting Get and List privileges to azdevops app projects principal on DEV and UAT

- CODEOWNERS
- src/core/env/dev/terraform.tfvars
- src/core/terraform.sh
> feat: Add fmlisco as a code owner

- src/k8s/selc_configmaps.tf
> modified env for USERVICE_PARTY_MANAGEMENT_URL

- src/domains/pnpg-app/06_selc_apim_pnpg.tf
- src/domains/pnpg-app/api/external_api_for_pnpg/v2/jwt_auth_op_policy_user_group.xml.tpl
- src/domains/pnpg-app/env/dev/terraform.tfvars
- src/domains/pnpg-app/env/prod/terraform.tfvars
- src/domains/pnpg-common/01_key_vault_operations.tf
- src/domains/pnpg-common/99_outputs.tf
> fix: PNPG Apim policy

- src/core/apim.tf
- src/core/env/uat/terraform.tfvars
> fix: AKS min node size, APIM add prod-pn-test

- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
Adding SAP to event hub in tfvars files for every environment
SAP will need to connect to our event hub in order to retrieve the billing informations for every institution
---
> Add sap to event_hubs

- src/core/apim.tf
- src/domains/pnpg-app/10_selc_configmaps.tf
- src/k8s/selc_configmaps.tf
- src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
- src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
- src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
> refactor base path

- src/core/99_variables.tf
- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
- src/core/redis_cache.tf
Upgrading rdis cache version from 4 to 6 
https://pagopa.atlassian.net/browse/SELC-2047
---
> fix: Upgrade redis version to 6

- src/core/01_network_0.tf
- src/core/99_variables.tf
- src/core/README.md
- src/core/env/prod/terraform.tfvars
Setting ddos configuration for prod
---
> Feat: Add new ddos_protection_plan var for vnet

- src/core/contracts_template/pn/1.0.0/pn-accordo_di_adesione-v.1.0.0.html
> modified hmtl text and added recipient code placeholder in pn contract

- src/domains/pnpg-app/10_selc_configmaps.tf
- src/domains/pnpg-common/01_key_vault_operations.tf
> fix: update agid medatada

- src/core/env/prod/terraform.tfvars
> fix: Update eventhub ip rules for Prod-io test

- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
> fix: Sap ip for eventhub

- src/k8s/selc_configmaps.tf
> fix: Update url mapping for party migration

- src/core/api/party_management/v1/party_op_policy.xml.tpl
- src/core/api/party_process/v1/party_op_policy.xml.tpl
- src/core/apim.tf
> fix: Add policy jwt for party apim

- src/core/env/prod/terraform.tfvars
> fix: PN eventhub prod

- src/core/api/ms_internal_api/v1/getInstitution_op_policy.xml.tpl
- src/core/apim.tf
- src/core/env/prod/terraform.tfvars
Updating apim endpoint from party to core
---
> fix: Apim internal removing party-process

- src/core/.terraform.lock.hcl
- src/core/02_dns_public.tf
- src/core/README.md
Adding new MX dns for external AWS SES service
---
> Add new dns MX for AWS SES

- src/domains/pnpg-app/00_secrets.tf
- src/domains/pnpg-app/10_selc_secrets.tf
- src/k8s/00_secrets.tf
- src/k8s/selc_secrets.tf
> feat: add aws_secret_key for sending mail on notification

- src/domains/pnpg-app/10_selc_secrets.tf
- src/domains/pnpg-app/env/prod/terraform.tfvars
- src/k8s/selc_secrets.tf
> Pnpg cie url prod

- src/domains/pnpg-app/10_selc_secrets.tf
> Add env NOTIFICATION_MANAGER_CONNECTOR_TYPE for sending mail by aws connector

- src/core/contracts_template/pagopa/1.0.0/pagopa-accordo_di_adesione_psp-v.1.0.0.html
Change CEO in PSP pagoPA contract's epigraph.
Given that the managing director of PagoPA has changed, it was necessary to make this change by changing the name that is reported in the epigraph of the contract.
---
> [SELC - 2513] - change CEO in PSP pagopa contract

- src/domains/pnpg-common/02_mongodb.tf
> feat: Add Index to Core CosmosDB Collection @PNPG

- src/core/.terraform.lock.hcl
- src/core/README.md
- src/core/api_product/prod-fd/policy.xml
- src/core/apim.tf
- src/domains/pnpg-common/README.md
Add Prod FD to enabled product list for calling External API V2
New vertical wants to integrate with selfcare external apis
---
> Add product fd

- src/core/api/ms_external_api/v2/open-api.yml.tpl
- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
Add new eventhub SC-Contracts-sap
Added a new dedicated eventhub for SAP, sc-contracts-sap.
Removed SAP from SC-Contracts eventhub
-Updated openApi Institution fields
Sap will no longer have access to sc-contracts eventhub
---
> Added new eventhub dedicated to SAP

- src/core/04_appgateway.tf
Removing ms-core from app gateway to protect micro service
---
> Remove ms-core from app gateway

- src/domains/pnpg-app/10_selc_configmaps.tf
set MAIL_TEMPLATE_PATH for pnpg
---
> refactor: set MAIL_TEMPLATE_PATH for pnpg

- src/k8s/selc_secrets.tf
Added secret references to sc-users connection string for external-interceptor
New topic was added and the microservice needs the secrets to authenticate into it
---
> added configurations to external-ionterceptor event secrets

- src/core/05_oauth.tf
Adding new key vault secret for azuread application issuer 
---
> adding new kv secret

- src/core/.terraform.lock.hcl
- src/core/api/ms_external_api/v2/getDelegationsUsingGET_op_policy.xml.tpl
- src/core/api/ms_external_api/v2/open-api.yml.tpl
- src/core/apim.tf
Added api to retrieve institution's delegations
---
> [SELC - 2700 ] added api to retrieve delegations

- src/domains/pnpg-app/.terraform.lock.hcl
- src/domains/pnpg-app/10_selc_secrets.tf
- src/k8s/.terraform.lock.hcl
- src/k8s/selc_secrets.tf
> feat: added STORAGE_TEMPLATE_URL

- src/domains/pnpg-app/80_tls_checker.tf
- src/domains/pnpg-app/README.md
- src/domains/pnpg-app/env/dev/terraform.tfvars
- src/domains/pnpg-app/env/prod/terraform.tfvars
- src/domains/pnpg-app/env/uat/terraform.tfvars
Update tls checker image version
---
> fix: Add new tls checker params

- src/k8s/00_secrets.tf
- src/k8s/README.md
- src/k8s/selc_secrets.tf
Added api key for zendesk integration.
This api key is necessary to integrate CMS Zendesk into self-care platform and retrieve contact form into support's section.
> Added secret key for zendesk integration

- src/domains/pnpg-app/10_selc_configmaps.tf
- src/domains/pnpg-app/10_selc_secrets.tf
- src/domains/pnpg-app/README.md
> feat: added pnpg aws key and national timeout

- src/domains/pnpg-app/.terraform.lock.hcl
- src/domains/pnpg-app/10_selc_configmaps.tf
set ENDPOINT_ERROR and ENDPOINT_SUCCESS as imprese.uat.notifichedigitali
---
> fix: set ENDPOINT_ERROR and ENDPOINT_SUCCESS

- src/core/api/ms_external_api/v2/open-api.yml.tpl
> [SELC - 2781]fix: updated open-api

- src/k8s/selc_secrets.tf
add secret reference for external interceptor
added a new producer to external interceptor, and the secret is needed for authenticating into the new topic
---
> add secret to external-interceptor

- src/core/api/selfcare_support_service/v1/open-api.yml.tpl
- src/core/api/selfcare_support_service/v1/sendSupportRequest_op_policy.xml.tpl
- src/core/apim.tf
added api support request to call /dashboard/v1/support
---
> feat: added api support request

- src/core/02_dns_public.tf
- src/core/README.md
- src/core/env/uat/terraform.tfvars
Added `azurerm_dns_ns_record` resource for `firmaconio.selfcare.pagopa.it`
---
> [SFEQS-1920] Add dns_ns_record for firmaconio_selfcare

- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
> add interop consumer to eventhub sc-contracts

- src/core/contracts_template/interop/2.1.0/interop-accordo_di_adesione-v.2.1.0.html
> [SELC - 2805] updated interop contract text

- src/aks-platform/env/dev01/terraform.tfvars
- src/aks-platform/env/prod01/terraform.tfvars
- src/aks-platform/env/uat01/terraform.tfvars
- migrazione middleware alle ultime versioni
- migrazione del control plane e dei nodi
Tenere aggiornate le versioni di k8s per evitare problemi di non supporto o sicurezza
---
> breaking: Migrazione UAT AKS 1.26

- src/core/api/ms_external_api/v2/getInstitution_op_policy.xml.tpl
- src/core/api/ms_external_api/v2/open-api.yml.tpl
> Release Production

- src/core/api/ms_external_api/v2/getInstitution_op_policy.xml.tpl
- src/domains/pnpg-app/06_selc_apim_pnpg.tf
- src/domains/pnpg-app/README.md
- src/domains/pnpg-app/api_product/pnpg_hotfix/policy.xml
add new apim product prod-pn-pg-hotfix
---
> Add new APIM product for pnpg

- src/aks-platform/env/prod01/terraform.tfvars
- upgrated middleware to last version
- node sys capacity upgrated to 2 nodes
- minor fix
---
> breaking: Aks upgrated 1.26

- src/core/contracts_template/io-sign/1.0.0/io_sign-accordo_di_adesione-v.1.0.0.html
updated pagopa manager name in io-sign contract epigraph 
---
> [SELC - 2857] updated pagopa manager name

- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
Adding IP mask on env terraform vars
---
> Adding event hub ip mask for interop

- src/core/api/ms_external_api/v2/open-api.yml.tpl
Modified open api for getDelegations in v2 external api
This change was necessary after updates into ms-core
> Modified open api for getDelegations in v2 external api

- src/core/03_network_aks_domains.tf
Adding ddos_protection_plan configuration
---
> adding ddos_protection_plan

- src/domains/pnpg-app/10_selc_configmaps.tf
- src/k8s/selc_configmaps.tf
add ms external interceptor url to internal url config map
---
> add ms-external-interceptor url to configMaps

- src/core/api/ms_external_api/v2/getUserInfoUsingGet_op_policy.xml.tpl
- src/core/api/ms_external_api/v2/open-api.yml.tpl
- src/core/apim.tf
Add getUser by id api to external api v2
External products needs to retrieve user PII using selfcare user unique id
---
> Add getUser by Id 

- src/core/api/ms_external_api/v2/open-api.yml.tpl
> [SELC - 2965] - added origin and originId to getInstitutions

- src/core/README.md
- src/core/api/ms_external_api/v2/open-api.yml.tpl
- src/core/cdn.tf
- src/k8s/.terraform.lock.hcl
- src/k8s/06_tls_cert_check.tf
- src/k8s/README.md
- src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
- src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
- src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
Added fields to getDelegations response
This change was necessary to allow support service to manage taxCode and institutionType of institution
> Added fields to getDelegations response

- src/core/api/ms_external_api/v2/open-api.yml.tpl
> Fix get user api name

- src/core/api/selfcare_support_service/v1/getInstitutionUsersUsingGET_op_policy.xml.tpl
- src/core/api/selfcare_support_service/v1/open-api.yml.tpl
- src/core/apim.tf
Added API to retrieve institution's users from institution identifier
This change was a specific request of support service
> Exposed new API to retrieve institution's users indipendently from product ID

- src/core/api/selfcare_support_service/v1/getInstitutionsByTaxCodeUsingGET_op_policy.xml.tpl
Fix institutions path in support api
Rewrite uri for api that retrieves institution according to tax code in input
> Fix institutions path in support api

- src/k8s/selc_configmaps.tf
Add externall api backend url to innerservice url configmap
external interceptor needs to internally call external api backend
---
> Add external_api backend url to innerservice urls

- src/core/contracts_template/interop/2.3.0/interop-accordo_di_adesione-v.2.3.0.html
Modified contract's template for interop 2.3
This change was necessary to adapt contract to new version
> Modified contract's template for interop 2.3

- src/core/README.md
- src/core/resources.tf
- src/core/resources/anac/data.csv
Data source file for new ANAC registry to onboard prod-interop SA
---
> Add anac csv resource

- src/core/api/selfcare_support_service/v1/getTokensFromProductUsingGET_op_policy.xml.tpl
- src/core/api/selfcare_support_service/v1/open-api.yml.tpl
- src/core/api/selfcare_support_service/v1/sendSupportRequest_op_policy.xml.tpl
- src/core/apim.tf
Added api to retrieve token by product id for support service api
This api was added to allow support service to retreiev info about onboardings for different products
> Added api to retrieve token by product id for support service api

- src/core/.terraform.lock.hcl
- src/core/00_github_runner.tf
- src/core/99_main.tf
- src/core/99_variables.tf
- src/core/README.md
- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
Nothing except for the use of the brand new Terraform module for GitHub runner infrastructure
Code reuse instead of duplication
---
> Switch to GitHub runner Terraform module

- src/core/README.md
- src/core/api/party_registry_proxy/party_op_policy.xml.tpl
- src/core/api/party_registry_proxy/v1/open-api.yml.tpl
- src/core/apim.tf
> feat: Adding new APIM party-registry-proxy

- src/core/resources/anac/data.csv
> Add new institutions

- src/core/api/ms_external_api/v2/open-api.yml.tpl
- src/core/api/selfcare_support_service/v1/getContract_op_policy.xml.tpl
- src/core/api/selfcare_support_service/v1/open-api.yml.tpl
Added AS institution type in open api.
A new institution type  - AS - has been added to manage onboarding for insurance companies. So open api documentation has been updated
> [SELC-3220] feat: added AS institution type in open api

- src/core/api/ms_internal_api/v1/core_op_policy.xml.tpl
- src/core/api/ms_internal_api/v1/open-api.yml.tpl
- src/core/api/party_registry_proxy/v1/open-api.yml.tpl
- src/core/apim.tf
**List of changes**
- add CreateDelegationUsingPost in internal-api
- add legalAddressUsingGET in registry-proxy-api
**Type of changes**
Add new API to Apim, add policy and operationId in configuration
**Env to apply**
Does this introduce a change to production resources with possible user impact?
> [SELC-3149] feat: add Api on Apim for migration Tool

- src/core/env/prod/terraform.tfvars
> Adding new IP mask for eventhub firewall on product FD

- src/core/02_dns_private.tf
- src/core/README.md
Add a DNS private zone to resolve Container App Environment running as internal
Container App cluster is running as internal, so no public endpoint is exposed. APIM and APPG needs a private DNS to resolve the DNS and forwarding requests to Container App Environment static IP 
---
> Add private DNS zone for Container App Environment

- src/core/README.md
- src/core/assets.tf
- src/core/env/dev/assets/login-alert-message.json
- src/core/env/prod/assets/login-alert-message.json
- src/core/env/uat/assets/login-alert-message.json
- src/domains/pnpg-app/05_assets.tf
- src/domains/pnpg-app/README.md
- src/domains/pnpg-app/env/dev/assets/login-alert-message.json
- src/domains/pnpg-app/env/prod/assets/login-alert-message.json
- src/domains/pnpg-app/env/uat/assets/login-alert-message.json
> Adding alert message json file

- src/domains/pnpg-app/env/prod/assets/login-alert-message.json
> Remove enable field for pnpg

- src/aks-platform/00_monitor.tf
- src/aks-platform/99_variables.tf
- src/aks-platform/README.md
- src/core/04_appgateway.tf
- src/core/README.md
- src/core/aks.tf
- src/core/events.tf
- src/core/monitor.tf
- src/core/postgres.tf
- src/domains/pnpg-app/00_monitor.tf
- src/domains/pnpg-app/99_variables.tf
- src/domains/pnpg-app/README.md
- src/k8s/locals.tf
> fiat: Update alert data

- src/core/env/prod/terraform.tfvars
> increment min and max capacity

- src/core/resources/anac/data.csv
> add new entry to procurement data source

- src/core/api/selfcare_support_service/v1/open-api.yml.tpl
Update open api for support service api
After changes in ms-core API, it was necessary to update documentation for support service about response objects.
> fix: Update open api for support service api

- src/core/api/ms_external_api/v2/open-api.yml.tpl
- src/core/apim.tf
> Add Logo to external-api.v2 to Institution resurce

- src/core/env/prod/assets/login-alert-message.json
Adding new error banner due to aruba down
---
> Update alert message on prod

- src/k8s/05_dns.tf
- src/k8s/README.md
> Migrating Aruba.it to google dns

- src/core/.terraform.lock.hcl
- src/core/02_dns_private.tf
- src/core/99_variables.tf
- src/core/README.md
Add an `A` record to the azurecontainerapps.io private DNS zone to resolve requests to the container app environment
The need to resolve domain into the container app environment static IP forces us to set an A DNS record in the private DNS zone
---
> Add DNS A record for azurecontainerapps.io

- src/core/api/ms_external_api/v2/open-api.yml.tpl
- src/core/api/ms_internal_api/v1/core_op_policy.xml.tpl
- src/core/api/ms_internal_api/v1/internal_jwt_base_policy.xml.tpl
- src/core/api/ms_internal_api/v1/open-api.yml.tpl
- src/core/api/selfcare_support_service/v1/open-api.yml.tpl
- src/core/apim.tf
- src/k8s/.terraform.lock.hcl
- src/k8s/99_variables.tf
- src/k8s/selc_configmaps.tf
- src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
- src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
- src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
- Add api for AutoApprovalOnboardingFromPDA in internal.api
- move createDelegation from external-v2 to internal
Need APi for injection tool
> [SELC-3290] feat: Add api for AutoApprovalOnboardingFromPDA in internal-api

- src/core/04_appgateway.tf
> Adding new ingress path due to new hub-spid-login ms

- src/core/api/ms_internal_api/v1/open-api.yml.tpl
- src/core/api/ms_internal_api/v1/postOnboardingInstitutionUsers_op_policy.xml.tpl
- src/core/api/selfcare_support_service/v1/open-api.yml.tpl
- src/core/apim.tf
Added POST /onboarding/users to internal api v1 
This api should be called from migration tool for adding users OPERATOR to new onboarding.
---
> Add onboarding users to internal api v1

- src/core/02_dns_private.tf
- src/core/99_variables.tf
- src/core/README.md
Removed  **resource azurerm_private_dns_a_record.private_dns_record_a_azurecontainerapps_io**
The resource **private_dns_record_a_azurecontainerapps_io** is closely linked to the creation of container app **onboarding-ms-ca**. Its lifecycle is managed by its repository, so we want the creation of private dns to also be handled within the container app's repository.
---
> remove onboarding_ms_ca record dns

- src/core/resources/anac/data.csv
> Add new institutions to ANAC data.csv

- src/core/assets.tf
- src/core/env/dev/assets/spid_idp_status.json
- src/core/env/prod/assets/spid_idp_status.json
- src/core/env/uat/assets/spid_idp_status.json
> Adding new resource for idp status

- src/core/assets.tf
- src/core/env/dev/assets/spid_idp_status.json
- src/core/env/prod/assets/spid_idp_status.json
- src/core/env/uat/assets/spid_idp_status.json
> Adding new resource for idp status (#522)

- src/core/README.md
- src/core/env/prod/spid/metadata.xml
> Add pub-op-full to metadata

- .identity/.terraform.lock.hcl
- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
Normalize identities IAC roles and get rid of `DEV` GitHub environment
Roles were not consistent across all environments and some of them were unneeded.
---
> Normalize variables for identity module

- src/core/api_product/io-premium/policy.xml
- src/core/apim.tf
> Adding product-io-premium and remove prod-test-io*

- src/core/02_dns_private.tf
- src/core/README.md
Set A record to resolve internal DNS to K8S load balancer IP. Fix a TF reference
Prepration for cluster upgrade
---
> [SELC-3340] Fix reference to selc A record for K8S internal DNS zone

- src/core/04_appgateway.tf
- src/core/99_variables.tf
- src/core/README.md
- src/core/apim.tf
- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
- src/core/outputs.tf
APIM and AppGateway will resolve IP address through an internal DNS instead of using IP address
Cluster is going to be updated and these changes are required
---
> [SELC-3340] Update APIM and AppGateway to new K8S endpoints

- src/k8s/99_variables.tf
- src/k8s/README.md
- src/k8s/health.tf
- src/k8s/health_ingress.tf
- src/k8s/ingress.tf
- src/k8s/selc_ingress.tf
- src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
- src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
- src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
Namespaces and hosts
Mandatory breaking changes for AKS >= v1.25
---
> [SELC-3340] K8S config for >= v1.25

- src/core/README.md
- src/core/env/dev/terraform.tfvars
- src/core/env/uat/terraform.tfvars
Kubernetes version
Migration happened 🎉
---
> [SELC-3340] Upgrade Kubernetes version

- src/core/env/prod/terraform.tfvars
Ip replaced with internal DNS
IP is now resolved through DNS
---
> [SELC-3341] Set new internal K8S DNS name as variable

- src/core/env/uat/terraform.tfvars
Set nodes autoscaler to 3-4
Need more resources
---
> [SELC-3470] Increase nodes count - UAT

- src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
- src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
- src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
token_exchange_billing_audience as "dev.portalefatturazione.pagopa.it"
---
> set token_exchange_billing_audience

- src/core/env/prod/terraform.tfvars
De facto - enable autoscaler on system node pool.
Keeping 3 nodes always on is useless
---
> [SELC-3467] Decrease minimum size of system node pool - PROD

- src/core/00_github_runner.tf
- src/core/README.md
GitHub runner module update
Latest module version contains important updates to support multiple environments of the same project
---
> [SELC-3471] Update GitHub runner module

- .identity/.terraform.lock.hcl
- .identity/01_github_identity.tf
- .identity/99_main.tf
- .identity/README.md
- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
Federates managed identites with all selfcare repos
Moving pipelines from devops to github is ahead of us, so they should be able to read and eventually change infrastructure using managed identities
---
> [SELC-3472] Update .identity config with all selfcare repos

- src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
- src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
- src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
Added /auth to billing uri redirect
---
> fix: set value billing uri redirect

- src/core/resources/anac/data.csv
> Add new ANAC file 2023-11-27

- src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
- src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
- src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
> fix: Token exchange url

- src/core/env/prod/assets/spid_idp_status.json
- src/core/monitor.tf
- src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
Updating list of IDPs that added new AGID metadata
---
> update ipd metatada list

- src/core/resources/anac/data.csv
> Updata anac file

- src/core/api/external_api_contract/v1/getContractUsingGet_op_policy.xml.tpl
- src/core/apim.tf
> Set IPs filter for getContrat API

- src/core/README.md
- src/core/apim.tf
- src/core/env/dev/terraform.tfvars
Update K8S version
Set autoscaler 1-3
K8S have been upgraded
Cluster now has two replicas per service and it may need to scale up and down
---
> [SELC-3582] Update AKS definition following the cluster version upgrade

- src/core/99_variables.tf
- src/core/README.md
- src/core/aks.tf
- src/core/env/prod/terraform.tfvars
Add missing properties
There was a drift between TF config and Azure resources
---
> [SELC-3584] Update AKS config - PROD

- src/core/api/selfcare_support_service/v1/getAllTokensUsingGET_op_policy.xml.tpl
- src/core/api/selfcare_support_service/v1/getUsersUsingGET_op_policy.xml.tpl
- src/core/api/selfcare_support_service/v1/open-api.yml.tpl
- src/core/apim.tf
Added API getAllTokens and getAllUsers
These API have been added to allow DL to retrieve information sent on topics SC-Contract and SC-Users
> [SELC-3692] feat: added API getAllTokens and getAllUsers

- src/core/api/ms_internal_api/v1/open-api.yml.tpl
- src/core/apim.tf
added updateUserStatusUsingPUT in internal api group
---
> [SELC-3786] Feat: added updateUserStatusUsingPUT in internal api group

- src/core/env/dev/assets/app-io-premium-plans.json
- src/core/env/prod/assets/app-io-premium-plans.json
- src/core/env/uat/assets/app-io-premium-plans.json
Added JSON app-io-premium plan prices
In order to have a json containing the app-io-premium price list for each environment of SelfCare
---
> [SELC-3612] feat: Added JSON app-io-premium plan prices

- src/core/monitor.tf
> Fix: Test url maps adding configuration for notifcation to opsgenie

- src/github-runner/README.md
- src/github-runner/container_app_environment.tf
- src/github-runner/container_app_jobs.tf
Update container app job TF modules
New modules contain new github runner image
---
> [EC-105] Update container app job modules

- src/core/.terraform.lock.hcl
- src/core/00_secrets.tf
- src/core/01_key_vault_0.tf
- src/core/01_key_vault_operations.tf
- src/core/01_network_0.tf
- src/core/01_network_pair.tf
- src/core/03_network_aks_domains.tf
- src/core/04_appgateway.tf
- src/core/99_main.tf
- src/core/README.md
- src/core/acr_docker.tf
- src/core/aks.tf
- src/core/apim.tf
- src/core/azure_devops_agent.tf
- src/core/cdn.tf
- src/core/container_apps.tf
- src/core/docker_registry_common.tf
- src/core/events.tf
- src/core/loadtests_resources.tf
- src/core/mongodb.tf
- src/core/monitor.tf
- src/core/postgres.tf
- src/core/redis_cache.tf
- src/core/storage_contracts.tf
- src/core/storage_logs.tf
- src/core/vpn.tf
> [EC-117] Upgrade Terraform modules and providers in core configuration

- .identity/README.md
- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
- .identity/github_managed_identity_cd.tf
- .identity/github_managed_identity_ci.tf
- .identity/variables.tf
Add managed identity federated with microservices repositories
A single managed identity for all microservices was required, all of them must perform the same tasks with same permissions
---
> [EC-160] Add managed identity for microservices pipelines

- src/core/api/ms_external_api/v2/open-api.yml.tpl
Update api-doc for API zendesk
> [SELC-3995] feat: update api-doc for API zendesk

- src/aks-platform/.terraform.lock.hcl
- src/aks-platform/00_monitor.tf
- src/core/monitor.tf
- src/domains/pnpg-app/00_monitor.tf
> Fix resources

- src/core/99_variables.tf
- src/core/README.md
- src/core/monitor.tf
- src/domains/pnpg-app/00_monitor.tf
- src/domains/pnpg-app/99_variables.tf
- src/domains/pnpg-app/README.md
Added alert on functions based on Exceptions for core and pnpg
---
> [SELC-4157] feat: alert on functions when an exception happens

- src/core/04_appgateway.tf
Changed the Regex in the rewrite rule  of the Application gateway
an MS-core API that contained "/onboarding" in the path was reachable from the external network due to the appgateway regex
---
> modified rewrite rule in appgateway

- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
Add selfcare-user repository
Use managed identity in pipelines
---
> Add Selfcare-user as GitHub federated repository

- src/core/README.md
- src/core/api/notification_event_api/v1/internal_jwt_base_policy.xml.tpl
- src/core/apim.tf
Adding new API Group Notification Event 
---
> feat: Add Notification Event to APIM

- src/domains/pnpg-app/10_selc_secrets.tf
- src/k8s/selc_secrets.tf
Added USER-REGISTRY-API-KEY for container apps migration. It is used by onboarding-backend.
---
> add user pdv key for ca

- src/core/mongodb.tf
> Upgrade mongo version to from 4.0 to 4.2

- src/core/README.md
- src/core/api_product/interop-atst/policy.xml
- src/core/apim.tf
Added new product to apim for interop attestazione
New product has been added to selfcare, and its a new testing product related to Interop, this need to access the external-apim v2, so it needs  an api key associated to them
---
> [SELC-4432] feat: Add new apim product for prod-interop-atst

- src/aks-platform/00_monitor.tf
- src/core/api/ms_external_api/v2/open-api.yml.tpl
- src/core/api/selfcare_support_service/v1/open-api.yml.tpl
- src/core/monitor.tf
- src/domains/pnpg-app/00_monitor.tf
> fix: Remove OPSGenie monitor and add New params to APIM getDelegations

- src/core/api/ms_external_api/v2/open-api.yml.tpl
- src/core/api/selfcare_support_service/v1/open-api.yml.tpl
> Add search param to getDelegationsUsingGET

- src/core/events.tf
Added secret for event hub keys in lower case
In order to avoid error for secrets with capital letters in container apps, a new secret has been added using lower case function for each key
---
> [SELC-4529] feat: added secret for event hub keys in lower case

- src/core/env/prod/terraform.tfvars
Adding new IP for prod-interop
---
> feat: Adding new IP for prod-interop-atst

- src/core/99_variables.tf
- src/core/README.md
- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
- src/core/eventhub_rds_vm.tf
- src/core/eventhub_rds_vm_script.sh
> Add eventhub proxy

- src/core/env/dev/terraform.tfvars
> Disable nexi ip on DEV

- src/core/env/prod/terraform.tfvars
> Replace onboarding dns name for new ca

- src/core/env/uat/terraform.tfvars
> fix ip nexi uat

- src/core/env/dev/terraform.tfvars
- src/domains/pnpg-app/env/dev/terraform.tfvars
Recovering Container App Env consumption for dev environment
---
> Migration to Container App Env consumption dev

- src/core/04_appgateway.tf
- src/core/99_variables.tf
- src/core/README.md
- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
- src/domains/pnpg-app/env/dev/terraform.tfvars
> Redirect hub-spid-login to Container App Environment

- src/core/env/uat/spid_testenv_conf/config.yaml
- src/core/spid-testenv.tf
> update spid test env on uat

- src/core/api/ms_external_api/v2/messageAcknowledgment_op_policy.xml.tpl
- src/core/api/notification_event_api/v1/open-api.yml.tpl
- src/core/apim.tf
Adding JWT creation on messageAcknowledgment_op_policy.xml
---
> [SELC-4700] Updating APIM

- src/core/env/uat/terraform.tfvars
- src/domains/pnpg-app/env/uat/terraform.tfvars
> Container App Env-001-uat

- src/core/env/uat/terraform.tfvars
- src/domains/pnpg-app/05_assets.tf
- src/domains/pnpg-app/assets/robots.txt
- src/domains/pnpg-app/env/uat/terraform.tfvars
Avoid google index on some pnpg uat pages
---
> [SELC-4710] Adding robots.txt to pnpg uat

- src/container-apps/README.md
- src/container-apps/_modules/container_app_environments/README.md
- src/container-apps/_modules/container_app_environments/container_app_environment_pnpg.tf
- src/container-apps/_modules/container_app_environments/container_app_environment_selfcare.tf
- src/container-apps/_modules/container_app_environments/data.tf
- src/container-apps/_modules/container_app_environments/main.tf
- src/container-apps/_modules/container_app_environments/outputs.tf
- src/container-apps/_modules/container_app_environments/variables.tf
- src/container-apps/_modules/networking/README.md
- src/container-apps/_modules/networking/data.tf
- src/container-apps/_modules/networking/locals.tf
- src/container-apps/_modules/networking/main.tf
- src/container-apps/_modules/networking/outputs.tf
- src/container-apps/_modules/networking/security_group_subnet_pnpg.tf
- src/container-apps/_modules/networking/subnet_pnpg.tf
- src/container-apps/_modules/networking/subnet_selfcare.tf
- src/container-apps/_modules/networking/variables.tf
- src/container-apps/dev/westeurope/.terraform.lock.hcl
- src/container-apps/dev/westeurope/README.md
- src/container-apps/dev/westeurope/locals.tf
- src/container-apps/dev/westeurope/main.tf
- src/container-apps/prod/westeurope/.terraform.lock.hcl
- src/container-apps/prod/westeurope/README.md
- src/container-apps/prod/westeurope/locals.tf
- src/container-apps/prod/westeurope/main.tf
- src/container-apps/uat/westeurope/.terraform.lock.hcl
- src/container-apps/uat/westeurope/README.md
- src/container-apps/uat/westeurope/locals.tf
- src/container-apps/uat/westeurope/main.tf
- src/core/env/prod/terraform.tfvars
> Container Apps environment as module

- src/domains/pnpg-app/env/prod/terraform.tfvars
> Replace PNPG api container app env url for prod

- src/core/contracts_template/interop/ivass/2.1.0/interop-accordo_di_adesione_as-v.2.1.0.html
Added new version 2.1.0 for IVASS onboarding
> [SELC-4211] feat: Added new version 2.1.0 for IVASS onboarding

- src/core/.terraform.lock.hcl
- src/core/api/ms_internal_api/v1/open-api.yml.tpl
> [SELC-4755] Adding new AS institutionType

- src/core/.terraform.lock.hcl
- src/core/api/ms_external_api/v2/getInstitutionProductUsersUsingGET_op_policy.xml.tpl
- src/core/apim.tf
> feat: forward getInstitutionProductUsersUsingGET to v2

- src/core/api/ms_external_api/v2/getInstitutions_op_policy.xml.tpl
- src/core/apim.tf
- src/domains/pnpg-app/06_selc_apim_pnpg.tf
- src/domains/pnpg-app/api/external_api_for_pnpg/v2/getInstitutions_op_policy.xml.tpl
* Forward getInstitutionsUsingGET to v2 on selc external v2
* Forward getInstitutionsUsingGET to v2 on pnpg external v2
---
> getInstitutionsUsingGET using v2

- src/core/api/ms_internal_api/v1/open-api.yml.tpl
- src/core/apim.tf
New API for send queue notification event from support team
---
> Add apim internal resendContractsByInstitutionIdAndTokenIdUsingPUT

- src/core/monitor.tf
- src/domains/pnpg-app/00_monitor.tf
Increment threshold to count 2
Avoid false alert on some functions that is completed after retry
---
> Increment threshold alert functions

- src/core/api/external_api_contract/v1/getContractUsingGet_op_policy.xml.tpl
- src/core/api/external_api_contract_public/v1/jwt_base_policy.xml.tpl
- src/core/api/jwt_base_policy.xml.tpl
- src/core/apim.tf
* Edit description of api external get-contract adding "limited by IP"
* Added new api get-contract that has not limitation by IP source
Project for conservazione sostitutiva need of api for getting file contract
---
> [SELC-4827] feat: added apim get contract public

- src/core/api/ms_external_api/v2/open-api.yml.tpl
- src/core/api/selfcare_support_service/v1/open-api.yml.tpl
> Added product role user info to openapi

- src/core/.terraform.lock.hcl
- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
> [SELC-4723] Adding new consumer

- src/core/mongodb.tf
Added indexes to selcMsCore Delegations collections on from and to
Query takes a lot fo RU/s for each query by from or to parameters. Indexes reduce RU needed. 
---
> added indexes to Delegations on from and to

- src/core/api/ms_external_api/v2/open-api.yml.tpl
Adding new TaxCode param as defined in MS-Core µs for getDelegationsUsingGET API
---
> [SELC-4520] Add new TaxCode param for getDelegationAPI

- src/core/contracts_template/io-sign/1.0.1/io_sign-accordo_di_adesione-v.1.0.1.html
- src/core/contracts_template/pn/2.0.0/pn-accordo_di_adesione-v.2.0.0.html
[SELC-4824] feat: Added taxCodeInvoicing in the template of invoicing products
It was necessary to collect this data during the onboarding phase for those products that invoice and, consequently, show it in their adhesion contract templates
---
[SELC-4824]: https://pagopa.atlassian.net/browse/SELC-4824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SELC-4824] feat: Added taxCodeInvoicing in the template of invoicing products

- src/core/README.md
- src/core/contracts_template/pagopa/1.0.0/pagopa-accordo_di_adesione_ec-v.1.0.0.html
- src/core/env/dev/terraform.tfvars
- src/core/env/uat/terraform.tfvars
- src/domains/pnpg-app/README.md
Updated contract for prod-pagopa and institutionType EC
---
> [SELC-4795] feat: Updated contract for prod-pagopa and institutionType EC

- src/core/env/dev/terraform.tfvars
> Enable dev konecta for conservazione

- src/core/mongodb.tf
Added new toTaxCode index on Delegation collection on ms-core DB
The index was added to improve performance for retrieving delegations based on taxCode field
---
> [SELC-4913] feat: add new index on toTaxCode field in Delegations Collection in mongo

- src/core/api/ms_external_api/v2/open-api.yml.tpl
Some endpoints are no longer used or are deprecated in favor of other endpoint.
---
> Deprecate some endpoints of External API v2

- src/core/api/selfcare_support_service/v1/open-api.yml.tpl
- src/core/apim.tf
- src/core/mongodb.tf
- src/domains/pnpg-app/06_selc_apim_pnpg.tf
- src/domains/pnpg-app/README.md
- added api to retrive institution onboardings to support module apim
This addition was necessary because the support team needs to take advantage of the following API
---
> [SELC - 5032] feat: added api to retrive institution onboardings to support module apim

- src/domains/pnpg-app/06_selc_apim_pnpg.tf
- src/domains/pnpg-app/api/pnpg_support_service/v1/open-api.yml.tpl
- Added getUserInfoUsingPOST in apim_pnpg_support_service_v2
We need to add getUserInfoUsingPOST also in pnpg_support Apim
---
> [SELC-5086] Feat: Added getUserInfoUsingPOST in apim_pnpg_support_service_v2

- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
> Enable PROD konecta for conservazione

- src/core/api/selfcare_support_service/v1/open-api.yml.tpl
- src/core/apim.tf
Adding new api for update some onboarding data from support api 
---
> [SELC-5088] Add new update onboarding api to apim support

- src/core/env/dev/terraform.tfvars
> Fix redirect /spid-login/v1 DEV

- .pre-commit-config.yaml
- src/aks-platform/.terraform.lock.hcl
- src/container-apps/dev/.terraform.lock.hcl
- src/container-apps/prod/westeurope/.terraform.lock.hcl
- src/core/env/dev/terraform.tfvars
- src/core/env/uat/terraform.tfvars
- src/github-runner/locals.tf
> Removed extra character in aks-platform terraform.lock.hcl file

- src/core/contracts_template/interop/user/2.0.0/interop-aggiunta-amministratore-v.2.0.html
> fix: Added missed dollar to var

- src/core/env/prod/terraform.tfvars
> Add new IP to eventhub rules

- src/core/contracts_template/pn/user/1.0.0/pn-aggiunta-amministratore-v.1.0.html
fix: vatnumber placeholder on add contract
In order to read correctly the var
---
> fix: vatnumber placeholder on add contract

- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
> Added identity selfcare-institution and remove unused repo

- src/core/mongodb.tf
- src/domains/pnpg-common/02_mongodb.tf
These collections are not used anymore
---
> Remove unused collection User and Token

- src/core/contracts_template/pn/user/1.0.0/pn-aggiunta-amministratore-v.1.0.html
Updated institutionMail placeholder into send contract for user
---
> Updated institutionMail placeholder into send contract for user

- src/core/contracts_template/pn/2.0.0/pn-accordo_di_adesione-v.2.0.0.html
Removed unecessary text from pn contract
---
> [SELC-5239] feat: Removed unecessary text from pn contract

- src/container-apps/_modules/networking/subnet_selfcare.tf
- src/container-apps/uat/westeurope/README.md
- src/container-apps/uat/westeurope/locals.tf
- src/container-apps/uat/westeurope/main.tf
- src/core/env/uat/terraform.tfvars
> chore: Move to Container App Env workload UAT

- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
> add infra private identity

- src/core/resources/enti_aggregatori_template_esempio.csv
> Added enti aggregatoti template csv

- src/container-apps/prod/westeurope/README.md
- src/container-apps/prod/westeurope/main.tf
- src/core/env/prod/terraform.tfvars
> chore: Move to Container App Env workload PROD

- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
- src/core/README.md
- src/core/mongodb.tf
- src/domains/pnpg-app/10_selc_secrets.tf
- src/domains/pnpg-app/99_variables.tf
- src/domains/pnpg-common/00_data.tf
- src/domains/pnpg-common/02_mongodb.tf
- src/domains/pnpg-common/README.md
- src/k8s/locals.tf
- src/k8s/selc_secrets.tf
Product microservice is not used anymore because we are migrating configuration into a json file
---
> [SELC-4388] refactor: Remove mongodb Products resources

- src/core/env/dev/assets/login-alert-message.json
- src/core/env/prod/assets/login-alert-message.json
- src/core/env/uat/assets/login-alert-message.json
New disservice banners for manage certificate expiration
To manage certificate expiration, banners have been added that could be used
---
> New disservice banners for manage certificate expiration

- .github/workflows/call_publish_contracts_template.yml
- .github/workflows/publish_contracts_template.yml
> feat: Add deploy contracts action

- .identity/README.md
- src/core/env/prod/terraform.tfvars
> [SELC-5461] chore: Adding new IP for eventhub consumer for prod-interop

- infra/repository/.terraform.lock.hcl
- src/core/README.md
- src/core/resources.tf
- src/core/resources/aggregates/prod-io_enti_aggregatori_template_esempio.csv
- src/core/resources/aggregates/prod-pagopa_enti_aggregatori_template_esempio.csv
- src/core/resources/aggregates/prod-pn_enti_aggregatori_template_esempio.csv
- added csv templates for aggegators for different products (prod-io, prod-pagopa, prod-pn)
- added "null_resource" "upload_resources_aggregates" resource in resources.tf
---
> [SELC-5437] feat: add csv templates for aggegators

- src/core/contracts_template/interop/prv/1.0.0/interop-accordo_di_adesione_prv-v.1.0.0.html
> [SELC-5406] feat: added template for prv interop contract

- src/core/env/prod/terraform.tfvars
Adding new IP for eventhub ip_mask
---
> [SELC-5556] Add new IP for eventhub ip_mask

- src/domains/pnpg-common/02_mongodb.tf
- src/domains/pnpg-common/env/prod/terraform.tfvars
Update cosmosdb configuration for production
---
> [SELC-5294] feat: Add multi AZ and zone redundant

- src/core/cdn.tf
- src/domains/pnpg-common/02_mongodb.tf
- src/domains/pnpg-common/env/prod/terraform.tfvars
Add CSP frame-ancestors avoiding loading selfcare web pages from another url
---
> [SELC-5294] feat: Add CSP frame-ancestors avoiding loading selfcare web pages from another url

- src/core/contracts_template/pagopa/1.0.0/pagopa-accordo_di_adesione_prv-v.1.0.0.html
> [SELC-5494] feat: Added template for accordo adesione prv

- src/core/99_main.tf
- src/core/azure_devops_agent.tf
> Updating resource azuread_service_principal using client_id

- src/core/contracts/template/pagopa/1.0.0/pagopa-accordo_di_adesione_prv-v.1.0.0.html
Added new params into contract PRV
---
> [SELC-5494] feat: Added new params into contract PRV

- src/core/contracts/template/io/2.4.3/io-accordo_di_adesione-v.2.4.3.html
- new version of IO contract (v.2.4.3) to include aggregates csv 
---
> [SELC-5664] feat: new version of IO contract to include aggregates csv 

- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
Added to dev/uat/prod eventhub a new topic Sc-UserGroups with relative" selfcare-wo" producer and "io" consumer
This PR aims to create a new topic about UserGroups record. It is needed to emit update to AppIO product about UserGroups
---
> [SELC-5743] feat: create topic Sc-UserGroups

- src/core/resources/aggregates/prod-io_enti_aggregatori_template_esempio.csv
updated the aggregates csv example for the the product IO
The required fields for uploading new aggregators for the IO product have been updated. Now, we only request the necessary information for searching in the IPA database
- [x ] Update configuration to existing resources
- [ x] DEV
- [x ] UAT
- [ x] PROD
- [ x] Yes, users may be impacted applying this change
- [ x] No
---
> [SELC-5673] Feat: changed aggregates csv example for IO

- src/core/contracts/template/pagopa/1.0.1/pagopa-accordo_di_adesione_prv-v.1.0.1.html
- add new version of pagopa contract for PRV to include aggregates csv link placeholder
---
> [SELC-5734] feat: add PRV prodPa contract version 1.0.1

- src/core/contracts/template/interop/prv/1.0.0/interop-accordo_di_adesione_prv-v.1.0.0.html
Fixed post rw for interop contract prv
---
> [SELC-5737] feat: Fixed post rw for interop contract prv

- src/core/contracts/template/io-sign/1.0.2/io_sign-accordo_di_adesione-v.1.0.2.html
Added new version of io-sign template v7
---
> [SELC-5843] feat: Added new version of io-sign template v7

- src/core/env/prod/assets/config.json
> Remove cat_c14 from available category list pr send product

- src/core/env/dev/assets/config.json
- src/core/env/prod/assets/config.json
- src/core/env/uat/assets/config.json
added L7 and L22 categories for prod-pn
there was a need to open membership to local health authorities
---
> [SELC-5891] feat: added L7 and L22 categories for prod-pn

- src/core/mongodb.tf
- src/domains/pnpg-common/02_mongodb.tf
removed modules for collection userGroups. 
Will be added a new module in the repo selfcare-user which will introduce the new collection UserGroups that will inherit same data and structure except an index .
---
> [SELC-5957] feat: removed modules for collection userGroups

- src/core/contracts_template/contracts/template/io-sign/1.0.3/io_sign-accordo_di_adesione-v.1.0.3.html
Fixed text into Art 7, comma 5
Added new template for io-sign
---
> [SELC-5892] feat: Added template io-sign 1.0.3

- src/core/mongodb.tf
- src/domains/pnpg-common/02_mongodb.tf
removed modules for database selcUserGroup
Will be added a new module in the repo selfcare-user which will introduce the new collection UserGroups that will inherit same data and structure except an index .
---
> [SELC-5957] feat: removed modules for database selcUserGroup

- src/core/contracts/template/pagopa/user/1.0.0/pagopa-aggiunta-amministratore-psp-v.1.0.0.html
[SELC-5807] feat: creation of new template for contract adding psp administrator
Add a new template contract into infra under the path src/core/contracts/template/pagopa/user/psp/1.0.0/pagopa-aggiunta-amministratore-psp-v.1.0.0.html
---
[SELC-5807]: https://pagopa.atlassian.net/browse/SELC-5807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SELC-5807] feat: creation of new template for contract adding psp administrator

- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
- .identity/github_branch_rules.tf
- src/core/README.md
- src/domains/pnpg-common/README.md
Remove unused protection on develop branch
In order to migrate Azure Devops with Githbu Action we need token-exchange-fe repo has a managed identity in azure subscription.
---
> [SELC-5999] feat: Added token-exchange-fe repository managed identity

- src/core/contracts_template/contracts/template/pagopa/1.0.2/pagopa-accordo_di_adesione_prv-v.1.0.2.html
Added checkbox (aggregator)
Deleted table not used
Fixed some html tags
Fixed template post RW
---
> [SELC-6109] feat: Added new template version for contract PRV

- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
- .identity/github_environment_ci.tf
- .identity/github_managed_identity_ci.tf
Adding managed identities and environment secrets for configure and enable github action for release config file for frontend
---
> [SELC-6191] Adding managed identities and environment secrets

- src/core/contracts_template/contracts/template/pagopa/1.0.3/pagopa-accordo_di_adesione_prv-v.1.0.3.html
Added new template version for PRV and GPU
---
> [SELC-6109] feat: Added new template for PRV

- src/core/contracts_template/contracts/template/pagopa/attachments/1.0.0/pagopa-checklist-v1.0.0.html
Updated template with manager Data
---
> [SELC-5614] fix: Updated template with manager Data

- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
- src/core/README.md
> [SELC-6001] Add Identity for selfcare-dashboard-admin-microfrontend

- src/core/env/dev/assets/login-alert-message.json
- src/core/env/prod/assets/login-alert-message.json
> Remove temporary IO and IO-PREMIUM

- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
> [SELC-6003] feat: Added dashboard-users-microfe repository managed identity

- src/core/contracts_template/contracts/template/io-premium/1.1.1/io-premium-accordo_di_adesione-v.1.1.1.html
Updated allegato 1 io-premium
---
> [SELC-6234] fix: updated allegato 1 io-premium

- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
> [SELC-6004] feat: Added onboarding-frontend repository managed identity

- src/core/monitor.tf
Avoiding to get error on terraform apply using custom sku
---
> [SELC-6315] Adding sku ignore changes

- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
> [SELC-6007] feat: Added pnpg-dashboard-fe repository managed identity

- .identity/README.md
- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
- .identity/github_managed_identity_cd.tf
- .identity/github_managed_identity_ci.tf
- .identity/variables.tf
> [SELC-6000] feat: Added selfcare-assistance-frontend repository managed identity

- src/core/env/dev/assets/product_institution_types.json
Add L8 and C14 categories to configuration file
- [x ] Update configuration to existing resources
- [ x] DEV
---
> [SELC-6391] feat: open onboarding to prod-pn for PA with categories L8 and C14

- .github/workflows/call_publish_contracts_template.yml
- .github/workflows/publish_contracts_template.yml
> fix: Remove AzCli action from publish contracts template

- src/core/env/dev/assets/config.json
- src/core/env/prod/assets/config.json
- src/core/env/uat/assets/config.json
[SELC-6345] feat: opening oboarding flow for new SEND categories
opening oboarding flow for new SEND categories L8 and C14
---
[SELC-6345]: https://pagopa.atlassian.net/browse/SELC-6345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SELC-6345] feat: opening oboarding flow for new SEND categories

- src/core/env/dev/assets/login-alert-message.json
- src/core/env/prod/assets/login-alert-message.json
> feat: removed warning banner prod io and io-premium

- .github/workflows/call_publish_web_assets.yml
- src/core/contracts-template.tf
Update github action for deploy assets config files.
---
> Fix deploy assets CDN

- src/core/resources/aggregates/prod-pn_enti_aggregatori_template_esempio.csv
Update csv
Removed the unnecesary colons from csv like instituion name, ipa cod, adress as they will be recuperated from IPA service.
---
> SELC-6583 feat: update aggregates csv example for prod-pn

- src/core/contracts_template/contracts/template/interop/2.3.2/interop-accordo_di_adesione-v.2.3.2.html
- src/core/contracts_template/contracts/template/interop/ivass/2.1.1/interop-accordo_di_adesione_as-v.2.1.1.html
- src/core/contracts_template/contracts/template/interop/prv/1.0.2/interop-accordo_di_adesione_prv-v.1.0.2.html
- src/core/contracts_template/contracts/template/interop/user/2.0.1/interop-aggiunta-amministratore-v.2.0.1.html
- src/core/contracts_template/contracts/template/io-sign/1.0.4/io_sign-accordo_di_adesione-v.1.0.4.html
- src/core/contracts_template/contracts/template/io-sign/user/1.0.1/io_sign-aggiunta-amministratore-v.1.0.1.html
- src/core/contracts_template/contracts/template/pagopa/1.0.4/pagopa-accordo_di_adesione_prv-v.1.0.4.html
Added new ref to pec into the following contracts
| Product| Type |
|:---:|:---:| 
|pagopa|prv - gpu|
|interop|default|
|interop|prv|
|interop|AS|
|interop|Add. Amm.|
|io-sign| default|
|io-sign| Add. Amm.|
---
> [SELC-6290] feat: Updated into contract ref to new pec

- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
> [SELC-6006] feat: Added pnpg-onboarding-fe repository managed identity

- .github/workflows/call_publish_web_assets.yml
> [SELC-6631] chore: Add aggregates sample file to web assets gh action

- .identity/env/dev/terraform.tfvars
- .identity/env/prod/terraform.tfvars
- .identity/env/uat/terraform.tfvars
> Move identity federations for frontend repos

- src/core/contracts_template/contracts/template/pagopa/user/psp/1.1.0/pagopa-aggiunta-amministratore-psp-v.1.1.0.html
Added new template's version for admin flow in case of PSP ---> 1.1.0
---
> [SELC-6705] feat: added new template's version for admin flow in case of PSP

- src/core/contracts_template/contracts/template/io/2.4.5/io-accordo_di_adesione-v.2.4.5.html
> [SELC-6790] feat: Updated contract for IO

- src/core/04_appgateway.tf
- src/core/README.md
> [SELC-6685] Manage ingress rules for Auth ms

- CODEOWNERS
- src/core/.terraform.lock.hcl
> [SELC-6825] Add codeowners

- src/core/resources/aggregates/prod-pagopa_enti_aggregatori_template_esempio.csv
-modify aggregates csv example for prod-pagopa removing unnecessarily fields
Removing unnecessarily fields
---
> [SELC-6404] feat: update aggregates csv example for prod-pagopa

- src/core/mongodb.tf
- upgrade mongo_server_version from 4.2 to 7
This change is required to align mongo_server_version  to the one currenly applied
---
> fix: upgrade mongo_server_version from 4.2 to 7

- src/core/mongodb.tf
This reverts commit 9ba9ba767935bc9762b441c658c9cab2951951dd.
Revert mongo_server_version from 7 to 4.2
---
> Revert "fix: upgrade mongo_server_version from 4.2 to 7 (#867)"

- src/core/mongodb.tf
- set mongo_server_version to 4.2
---
> fix: set mongo_server_version to 4.2

- src/core/.terraform.lock.hcl
- src/core/01_key_vault_operations.tf
- src/core/05_oauth.tf
- src/core/99_variables.tf
- src/core/contracts-template.tf
- src/core/monitor.tf
- src/core/storage_logs.tf
- src/core/vpn.tf
> [SELC-7053] Deleting resources migrated

- src/core/env/dev/terraform.tfvars
- Added interop to SC-Users in DEV
---
> Added interop to SC-Users in DEV

- src/core/contracts_template/contracts/template/pagopa/user/psp/1.1.0/pagopa-aggiunta-amministratore-psp-v.1.1.0.html
- src/core/contracts_template/contracts/template/pagopa/user/psp/1.1.1/pagopa-aggiunta-amministratore-psp-v.1.1.1.html
Updated contract for user psp. In particular the input field "sede legale" was filled with the correct placeholder ${address}
---
> Updated contract for user psp

- src/core/04_appgateway.tf
> Allow Internal path as APIM route

- src/core/contracts_template/contracts/template/interop/user/2.0.2/interop-aggiunta-amministratore-v.2.0.2.html
[SELC-7150] Feat: update the Administrator Appointment contract for PDND
[SELC-7150] Feat: update the Administrator Appointment contract for PDND
---
[SELC-7150]: https://pagopa.atlassian.net/browse/SELC-7150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-7150]: https://pagopa.atlassian.net/browse/SELC-7150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SELC-7150] Feat: update the Administrator Appointment contract for PDND

- src/core/mongodb.tf
- Create compoud index "to", "status", "type", "productId", "createdAt"
- Create compoud index "from", "status", "type", "productId", "createdAt"
Index required by new getDelegators and getDelegates APIs
---
> [SELC-7377] Created new indexes for Delegations collection

- src/core/env/dev/assets/config.json
- src/core/env/prod/assets/config.json
- src/core/env/uat/assets/config.json
- added ateco codes to config.json
A new node has been added to the configuration file to insert the ATECO codes allowed on AR
---
> [SELC-7259] feat: added ateco codes to config.json

- src/core/env/dev/assets/config.json
- src/core/env/prod/assets/config.json
- src/core/env/uat/assets/config.json
> feat: updated ateco codes to config.json

- src/core/contracts_template/contracts/template/interop/ivass/2.2.0/interop-accordo_di_adesione_as-v.2.2.0.html
> [SELC-7185] feat: Formatted css for contract

- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
Adding new consumer to SC-User, SC-Contracts and SC-UserGroups queue.
---
> [SELC-7533] Adding piattaforma-unitaria to selfcare eventhub

- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
> [SECL-7550] feat: Adding configuration for DAPR eventhub consumer

- src/core/env/dev/assets/config.json
- src/core/env/prod/assets/config.json
- src/core/env/uat/assets/config.json
…pecific config files
[SELC-7654] Feat: Add prod-interop IPA configuration to environment-specific config files
Added an IPA category for the intitutionType GSP and the product 'prod-interop'
---
[SELC-7654]: https://pagopa.atlassian.net/browse/SELC-7654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SELC-7654] Feat: Add prod-interop IPA configuration to environment-specific config files
