pagopa/selfcare-infra

src/core/api/dashboard/v1/dashboard-openapi.json.tpl
src/core/apim.tf

dashboard added to APIm

---

src/core/aks.tf
src/core/env/dev/terraform.tfvars
src/core/env/prod/terraform.tfvars
src/core/env/uat/terraform.tfvars
src/core/variables.tf

autoscaling configurable
DEV and UAT (?) will not use it
PROD configuration to be defined
---

aks autoscaling configured

---

src/k8s/selc_configmaps.tf

configured hubSpidLogin to redirect to error login page
---

redirect to login-fe when idp return an error

---

src/k8s/selc_configmaps.tf
src/k8s/selc_ingress.tf
src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
src/k8s/variables.tf

added b4f-onboarding configuration
---

B4f onboarding

---

src/k8s/selc_configmaps.tf

Change the variable SPID_ATTRIBUTES used by hub-spid-login-ms to minimize spid assertion requested to IDP.
Request only used information about user to IDP through spid
- [x ] Update configuration to existing resources
---

[SELC-284] Remove unused data from spid info

---

.devops/code-review-pipelines.yml
.devops/deploy-pipelines.yml

enable uat

---

src/core/security.tf
src/core/utils/sh/renew-jwt.sh
src/k8s/selc_secrets.tf
src/modules/jwt/main.tf

Agid cert self signed

---

src/core/env/dev/terraform.tfvars
src/core/env/prod/terraform.tfvars
src/core/env/uat/terraform.tfvars
src/core/main.tf
src/core/mongodb.tf
src/core/variables.tf

- add cosmos zone redundant
- add cosmos secondary region
prod settings
---

Cosmos review

---

src/core/appgateway.tf

fixed notification-manager path
---

fixed notifications path changed into ms-notification-manager

---

src/core/env/dev/spid_testenv_conf/config.yaml
src/core/env/dev/terraform.tfvars
src/core/env/prod/terraform.tfvars
src/core/env/uat/spid_testenv_conf/config.yaml
src/core/env/uat/terraform.tfvars
src/core/spid-testenv.tf
src/core/variables.tf
src/modules/spid_testenv/spid-testenv.tf
src/modules/spid_testenv/variables.tf

SELC-458 fixed trigger on spidTestEnv to ignore environment specific configuration
---

Selc 458 fix spid testenv trigger

---

src/core/env/uat/terraform.tfvars

Added details for Interop domain delegation for UAT environment
Interop project needs to configure its DNS as `interop.uat.selfcare.pagopa.it`
A PR for production environment will follow
---

PIN-1456: Interop UAT domain delegation

---

src/core/mongodb.tf

- mongodb ignore autoscale settings
Cosmosdb now are manged manually to avoid problems with terraform an decrease costs
---

feat: Cosmosdb ignore autoscale settings

---

src/core/99_variables.tf
src/core/README.md
src/core/docker_registry_common.tf
src/core/env/dev/terraform.tfvars
src/core/env/prod/terraform.tfvars
src/core/env/uat/terraform.tfvars

- Fix the discrepancy between CIDR_subnet in Terraform template and existing configurations for every environment.
- Added network_rule_set to docker_registry_common for alignment with active configuration
---

fix cidr_subnet_private_endpoints

---

src/core/README.md
src/core/env/dev/terraform.tfvars
src/k8s/00_secrets.tf
src/k8s/README.md
src/k8s/selc_secrets.tf

Added new secret for backoffice pagopa subscription key.
This change is necessary to allow dashboard-backend microservice to invoke backoffice apis.

Added secrets for backoffice pago pa

---

src/domains/pnpg-app/10_selc_secrets.tf

set storage credentials for retrieving template and sending mail
Move sending mail @ms-core
---

fix: pnpg storage credentials for sending mail

---

src/core/api/ms_internal_api/v1/open-api.yml.tpl

Added x-selfcare-uid into open-api for auto approval onboarding.
This parameter is necessary to retrieve authentication and test api into apim

Fix parameter for auto approval onboarding into open-api

---

src/core/api/selfcare_support_service/v1/open-api.yml.tpl
src/core/api/selfcare_support_service/v1/postOnboardingInstitutionUsers_op_policy.xml.tpl
src/core/apim.tf

Added api POST /onboarding/users that call ms-core/v1//onboarding/users
This api adds users to the registry if they are not present and associates them with the institution and product contained in the body. It is useful for operations when we have to add SUB_DELEGATE to institution that has an onboarding on prod-interop
---

[SELC-3174] feat: added api onboarding users

---

src/core/monitor.tf

Currently Selfcare alerts are not explained with runbook.
---

Removing web hoot opsgenie from alerts

---

.identity/.terraform.lock.hcl
.identity/01_github_identity.tf
.identity/99_locals.tf
.identity/99_variables.tf
.identity/README.md
.identity/env/dev/backend.tfvars
.identity/env/dev/terraform.tfvars
.identity/env/prod/backend.tfvars
.identity/env/prod/terraform.tfvars
.identity/env/uat/backend.tfvars
.identity/env/uat/terraform.tfvars
src/core/01_key_vault_0.tf
src/core/README.md

Remove duplicated code and add a reference to [this PR](https://github.com/pagopa/terraform-azurerm-v3/pull/165).
Add federated credentials for both selfcare-infra and selfcare-onboarding repos.
Replace terraform state file
More than a single repository shall be able to use the same managed identity dedicated to a specific domain/project. New module version already supports it, so it worths to refactor this module.
Ex terraform state file was definitely wrong. It's all about infra and not apps
---

Refactor Identity Module

---

.identity/README.md
.identity/env/prod/terraform.tfvars
src/core/02_dns_public.tf
src/core/README.md
src/k8s/.terraform.lock.hcl
src/k8s/00_certificates.tf
src/k8s/99_variables.tf
src/k8s/README.md
src/k8s/selc_secrets.tf
src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars

Add a Kubernetes secret for each certificate required
New certificates have been released for `selc.internal.dev/uat.selfcare.pagopa.it` domain, and they need to be added to the K8S cluster as secrets
---

Add TLS certificates to K8S for ingresses

---

src/k8s/01_serviceaccounts.tf

Update service account used by Azure DevOps with god role over `poddisruptionbudgets` in `policy` api group
Azure DevOps should be able to set PDB policies
---

[SELC-3340] Update roles on AZOPS service account

---

src/k8s/.terraform.lock.hcl
src/k8s/99_main.tf
src/k8s/README.md

Upgrade TF Kubernetes provider to v2.18
Older versions are not compatible with Kubernetes versions >= v1.25.x
---

[SELC-3340] Upgrade terraform kubernetes provider

---

src/k8s/99_variables.tf
src/k8s/README.md
src/k8s/selc_configmaps.tf
src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars

**List of changes**
- added billing_url and billing_audience in env
**Motivation and context**
To access new Billing BO, a new API is required which builds a jwt that can be used for this portal and which contains the list of invoiceable products related to logged user, so for this API we need to have 2 new env variables
**Type of changes**
-  Add new var in jwt_exchange config map
**Env to apply**
**Does this introduce a change to production resources with possible user impact?**
**Does this introduce an unwanted change on infrastructure? Check terraform plan execution result**

[SELC-3407] Feat: added billing_url and billing_audience in env

---

src/core/api/selfcare_support_service/v1/getUserInfoUsingGet_op_policy.xml.tpl
src/core/api/selfcare_support_service/v1/open-api.yml.tpl
src/core/apim.tf

Added api getUserById into support service api
This API has been added to allow support service to retrieve user's info by internal identifier.

[SELC-3450] feat: added api getUserById into support service api

---

src/domains/pnpg-app/00_secrets.tf
src/domains/pnpg-app/10_selc_configmaps.tf
src/domains/pnpg-app/10_selc_secrets.tf
src/domains/pnpg-app/99_variables.tf
src/domains/pnpg-app/env/dev/terraform.tfvars
src/domains/pnpg-app/env/prod/terraform.tfvars
src/domains/pnpg-app/env/uat/terraform.tfvars
src/k8s/00_secrets.tf
src/k8s/99_variables.tf
src/k8s/selc_configmaps.tf
src/k8s/selc_secrets.tf
src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars

**List of changes**
added configMap and secret for anac-ftp
**Motivation and context**
In order to avoid manual update of anac csv file, we have to retrieve it from ftp. We need env variables to estabilish this connection to sftp server.
**Type of changes**
Add new configMap anc secrets
**Env to apply**
**Does this introduce a change to production resources with possible user impact?**
**Does this introduce an unwanted change on infrastructure? Check terraform plan execution result**

[SELC-3487] Feat: add configMap and secret for anac-ftp

---

src/core/env/uat/terraform.tfvars

AKS version upgrade
Autoscaler enabled
AKS has been upgraded, these changes reflect changes made by Az portal
---

[SELC-3583] Update AKS UAT config to match real infra after AKS upgrade

---

src/core/api/ms_external_api/v2/getInstitution_op_policy.xml.tpl
src/core/api/ms_external_api/v2/getInstitutions_op_policy.xml.tpl
src/core/apim.tf

- modify key LOGO_URL and its value in API External v2
The URL previously used (the CDND storage url) is not externally accessible. Being the API exposed externally, the URL was changed with another one externally accessible.
---

[SELC-3307] feat: modify url key  in API External v2

---

src/core/01_key_vault_0.tf

Admins needs to manage secrets on keyvault, even restore them
Admin can't restore secrets?
---

[EC-100] Give all kv secrets permissions to selfcare admin groups

---

.github/workflows/call_code_review.yml

Add explicit TF init step to pr pipelines
For some reason, selfcare's terraform.sh file doesn't perform an `init` when the `plan` command is given
---

[EC-109] Add explicit TF init to code review pipeline

---

src/core/api/ms_internal_api/v1/open-api.yml.tpl
src/core/apim.tf

- remove autoApprovalOnboarding  from apim_internal_api_ms_v1 module
- remove autoApprovalOnboarding api from intefrnal open-api
This api was not invoked.
---

[SELC-4015] feat: remove autoApprovalOnboarding api from internal apim

---

src/core/api/ms_internal_api/v1/open-api.yml.tpl
src/core/apim.tf

Added autoapproval endpoint in API internal
It was removed wrongly but it is used by onboarding-interceptor
---

[SELC-4015] fix: recover autoapproval internal

---

.identity/README.md
.identity/data.tf
.identity/github_managed_identity_cd.tf
.identity/github_managed_identity_ci.tf
src/aks-platform/README.md
src/core/README.md
src/domains/pnpg-app/README.md

Add KeyVault access policy for `selc-x-ms-github-identity-cx`, both pnpg and selc keyvaults
Missing policies
---

[EC-170] Add missing policies to KeyVault to allow access to GitHub identities

---

src/core/api/ms_external_api/v2/getInstitutionProductUsersUsingGET_op_policy.xml.tpl
src/core/api/ms_external_api/v2/open-api.yml.tpl

Re userIdForAuth is not required for API getInstitutionProductUsersUsingGET because this value is not currently used.
---

fix: Remove userIdForAuth from getInstitutionProductUsersUsingGET

---

src/core/api/ms_internal_api/v1/open-api.yml.tpl
src/core/apim.tf

Added createdAt API to internal APIM
This API will be invoked by a tool to update the activatedAt field in Token collection
---

[SELC-4322] feature: Added createdAt API to internal APIM

---

src/core/04_appgateway.tf

hub spind login on Container App env does not working so temporally we maintain redirect to AKS
---

Disable redirect hub spind login to Container App env 

---

src/domains/pnpg-app/00_monitor.tf
src/domains/pnpg-app/99_variables.tf

* Rename pnpg_error_5xx with http_error_5xx
* Added unhealthy_error_503 when receive 503 error
Sporadic 503 errors can be disregarded, as they result in false positives for 500-type errors
---

Added alert when a resource fails health check returning 503 error

---

src/core/04_appgateway.tf
src/core/README.md

Make app gateway point to apim v2 in dev
We are currently migrating the development environment's APIM to v2 compute platform.
For this reason, only the dev app gateway must be changed, leaving UAT and Prod untouched.
---

[EC-233] - Make app gateway point to apim v2 in dev

---

src/core/04_appgateway.tf
src/core/env/uat/terraform.tfvars

[EC-233] Make uat appgateway point to v2 apim

---

src/core/04_appgateway.tf

[EC-233] - Make prod appgateway point to v2 apim

---

.identity/github_managed_identity_cd.tf
.identity/github_managed_identity_ci.tf

Added get and list of selfcare's keyvault certificates to CI/CD managed identities
The APIM v2 migration being executed in the selfcare-external-api-backend repository requires the CI pipeline to share the terraform plan results with the team.
Currently, the [CI doesn't work correctly](https://github.com/pagopa/selfcare-external-api-backend/actions/runs/9613545166/job/26516507938) due to missing permissions like the aforementioned ones.
---

[EC-233] - Add certificate get and list permissions for kv certificates in cicd identity

---

src/core/02_nat.tf
src/core/README.md
src/core/aks.tf
src/core/outputs.tf

Some API deployed on AKS are now migrated to Azure Function and they need to still use the same outbound IP from AKS.
---

[SELC-5157] Move aks_outbound to onboarding-fn

---

src/container-apps/_modules/container_app_environments/README.md
src/container-apps/_modules/container_app_environments/container_app_environment_pnpg.tf
src/container-apps/_modules/container_app_environments/container_app_environment_selfcare.tf
src/container-apps/_modules/container_app_environments/variables.tf
src/container-apps/_modules/networking/README.md
src/container-apps/_modules/networking/data.tf
src/container-apps/_modules/networking/subnet_selfcare.tf
src/container-apps/dev/westeurope/README.md
src/container-apps/dev/westeurope/main.tf
src/container-apps/prod/westeurope/main.tf
src/container-apps/uat/westeurope/main.tf
src/core/env/dev/terraform.tfvars

* Added a workload profile.
* Renamed the environment by adding a suffix 002
* Added association IP with NAT Gateway
This change is required to migrate the container app environment to a new environment with a workload profile. This migration ensures that HTTP calls exit with a predefined IP address.
---

Migrate Container App Environment DEV to New Workload Profile Environment

---

src/core/99_main.tf

adding
provider "azurerm" {
features {}
skip_provider_registration = true
} 
https://pagopa.atlassian.net/wiki/spaces/DEVOPS/pages/463241875/Terraform+Troubleshooting+FAQs#%5CuD83E%5CuDD14-Problem%3A-Error-ensuring-Resource-Providers-are-registered
---

Workaround for oldest azurerm version required by terraform-module

---

src/core/env/dev/assets/product_institution_types.json
src/core/env/uat/assets/product_institution_types.json

Add GPU to the list of allowed instituion types for prod pagopa on dev and uat
To allow onboarding as a GPU from dashboard "avaible products" section for the product pagopa
- [ x] Update configuration to existing resources
- [x ] DEV
- [x ] UAT
---

[SELC-6074] Feat: enable onboarding for GPU in prod pagopa dev/uat

---

src/core/env/prod/assets/product_institution_types.json
src/core/env/uat/assets/product_institution_types.json

[SELC-6391 open onboarding to prod-pn for L8,C14 categories](https://github.com/pagopa/selfcare-infra/pull/839/commits/cfc3ea294cfc53766203fe882265f799a60990de)
opening prod-pn oboarding flow for  categories L8 and C14
---

[SELC-6391] feat: open onboarding to prod-pn uat/prod

---

.identity/github_managed_identity_cd.tf
.identity/github_managed_identity_ci.tf

This pull request grants additional permissions to our federated GitHub Actions workflows.
Specifically, it updates the permissions to allow the actions to access secrets required for their successful execution. This change is necessary to enable new functionalities that rely on secure credentials.
- Updated permission scopes for the federated identity configuration.
- Ensured that workflows can now securely retrieve necessary secrets.
---

[SELC-7498] Add new permissions for federated GitHub Actions to access secrets
